name: C Program CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

- name: Compile all C files separately
  run: |
    for file in *.c; do
      name=$(basename "$file" .c)
      gcc -Wall -Wextra "$file" -o "$name"
    done



    - name: Run the program
      run: ./program
