name: C Program CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile C program
      run: gcc -Wall -Wextra -o program main.c

    - name: Run the program
      run: ./program
